# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-23 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='board.Board'),
        ),
    ]
