# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-31 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
       
    ]
