# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20181031_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='attribute_description',
            new_name='board_description',
        ),    ]
