# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20181101_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content_rating_1_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='content_rating_2_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='content_rating_3_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='content_rating_4_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='content_rating_5_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='source_rating_1_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='source_rating_2_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='source_rating_3_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='source_rating_4_weight',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='source_rating_5_weight',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
