# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-01 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20181101_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='tempslugforboard', max_length=160),
            preserve_default=False,
        ),
    ]
