# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-18 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='attribute.Attribute'),
        ),
    ]
