# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-05 03:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Tags')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=150)),
                ('website', models.URLField()),
                ('organisation', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('current_position', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('publications', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('associations', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('skills', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('certifications', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('languages', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('interests', models.ManyToManyField(related_name='UserProfile', to='accounts.Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
