# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-09 01:59
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=django.contrib.auth.models.User, unique=True),
        ),
    ]
