# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-23 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0014_auto_20180813_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='comment',
        ),
    ]
