# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-25 21:27
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0015_remove_evidence_comment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='evidence',
            managers=[
                ('evrating', django.db.models.manager.Manager()),
            ],
        ),
    ]
