# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-26 22:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0016_auto_20180925_2127'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='evidence',
            managers=[
            ],
        ),
    ]
