# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0017_auto_20180926_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_1',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_1_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_2',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_2_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_3',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_3_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_4',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_4_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_5',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_5_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='key_finding1',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='key_finding2',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='key_finding3',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_1',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_1_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_2',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_2_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_3',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_3_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_4',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_4_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_5',
            field=models.CharField(blank=True, choices=[('1', 'Very Weak'), ('2', 'Weak'), ('3', 'Moderate'), ('4', 'Strong'), ('5', 'Very Strong')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_5_comment',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='research_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
