# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0023_auto_20181029_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_1',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_2',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_3',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_4',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='content_rating_5',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_1',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_2',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_3',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_4',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='source_rating_5',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
    ]
