# This file is included in-line in the env section of deployment.yaml
# if .Values.generatedBindings.enabled is true.
- name: IBM_APM_SERVER_URL
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_server_url
      optional: true
- name: IBM_APM_KEYFILE
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_keyfile
      optional: true
- name: IBM_APM_KEYFILE_PASSWORD
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_keyfile_password
      optional: true
- name: IBM_APM_INGRESS_URL
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_ingress_url
      optional: true
- name: IBM_APM_ACCESS_TOKEN
  valueFrom:
    secretKeyRef:
      name: apm-server-config
      key: ibm_apm_access_token
      optional: true
- name: service_postgre
  valueFrom:
    secretKeyRef:
      name: binding-evidence-base-postgresql-1531943532987
      key: binding
      optional: true
- name: service_weather_company_data
  valueFrom:
    secretKeyRef:
      name: binding-evidence-base-weatherinsights-1531938964906
      key: binding
      optional: true
